# Rock, Paper, Scissors

The game *Rock, papaer, scissors* has the following playoff Matrix.

$$ RPS=\begin{bmatrix} 0 & -1 & 1\\ 1 & 0 & -1 \\ -1 & 1 & 0 \end{bmatrix}$$

Determine the strategy for  $P_1$  and  $P_2$  as well as the game value "$v$"

In [2]:
import numpy as np
from pulp import *

pm=np.array([[ 0,-1, 1],
             [ 1, 0,-1],
             [-1, 1, 0]])

minim_row=np.array([0,0,0])
for i in range(0,len(pm)):
    minim_row[i]=min(pm[i])
    
min_tot=min(minim_row)

pm1=pm+abs(min_tot)

print("Game Matrix:")
print("")
print(pm)
print("")
print("-----------------------------------------------------------------")
print("Equivalent Game Matrix:")
print("")
print(pm1)
print("")
print("-----------------------------------------------------------------")

probx=LpProblem("Game X", LpMinimize)
#The variables are created:
x_1=LpVariable("X_1",0,None)
x_2=LpVariable("X_2",0,None)
x_3=LpVariable("X_3",0,None)
 
#The objective function is added
probx += x_1+x_2+x_3

#Subject to restrictions:
probx +=pm1[0][0]*x_1+pm1[1][0]*x_2+ pm1[2][0]*x_3 >=1
probx +=pm1[0][1]*x_1+pm1[1][1]*x_2+ pm1[2][1]*x_3 >=1
probx +=pm1[0][2]*x_1+pm1[1][2]*x_2+ pm1[2][2]*x_3 >=1

#Solution:
probx.solve()

vx=1/value(probx.objective)
print("Game for Player 1")
print ("")
print ("Game value of Equivalent Game Matrix'v'=", vx)
print ("")
print ("Game value Game Matrix 'w'=", vx-abs(min_tot))
print ("")

x=probx.variables()
X1=vx*(x[0].varValue)
X2=vx*(x[1].varValue)
X3=vx*(x[2].varValue)


print ("P1 Strategy:")
print("")
print ("X1=",X1)
print ("X2=",X2)
print ("X3=",X3)

print ("")
print("-----------------------------------------------------------------")

proby=LpProblem("Game Y", LpMaximize)
#The variables are created:
y_1=LpVariable("Y_1",0,None)
y_2=LpVariable("Y_2",0,None)
y_3=LpVariable("Y_3",0,None)
 
#The objective function is added
proby += y_1+y_2+y_3

#Subject to restrictions:
proby +=pm1[0][0]*y_1+pm1[0][1]*y_2+ pm1[0][2]*y_3 <=1
proby +=pm1[1][0]*y_1+pm1[1][1]*y_2+ pm1[1][2]*y_3 <=1
proby +=pm1[2][0]*y_1+pm1[2][1]*y_2+ pm1[2][2]*y_3 <=1

#Solution:
proby.solve()

vy=1/value(proby.objective)
print("Game for Player 2")
print ("")
print ("Game value of Equivalent Game Matrix'v'=", vy)
print ("")
print ("Game value Game Matrix 'w'=", vy-abs(min_tot))
print ("")

y=proby.variables()
Y1=vy*(y[0].varValue)
Y2=vy*(y[1].varValue)
Y3=vy*(y[2].varValue)


print ("P2 Strategy:")
print("")
print ("Y1=",Y1)
print ("Y2=",Y2)
print ("Y3=",Y3)

Game Matrix:

[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]

-----------------------------------------------------------------
Equivalent Game Matrix:

[[1 0 2]
 [2 1 0]
 [0 2 1]]

-----------------------------------------------------------------
Game for Player 1

Game value of Equivalent Game Matrix'v'= 1.0000000100000002

Game value Game Matrix 'w'= 1.00000001613e-08

P1 Strategy:

X1= 0.3333333333333333
X2= 0.3333333333333333
X3= 0.3333333333333333

-----------------------------------------------------------------
Game for Player 2

Game value of Equivalent Game Matrix'v'= 1.0000000100000002

Game value Game Matrix 'w'= 1.00000001613e-08

P2 Strategy:

Y1= 0.3333333333333333
Y2= 0.3333333333333333
Y3= 0.3333333333333333

