# Example 9.6.1

$P_1$ nd $P_2$ each extend either one, two, or three fingers and the difference in the numbers put forth is computed. If this difference is 0, the payoff is 0; if the difference is 1, the player putting forth the smaller amount wins 1; and if the difference is 2, the player putting forth the larger amount wins 2. 

Each player has 3 pure strategies. Let $s_i$ denote $P_1$'s pure strategy of extending $i$ finguers, $1\leq i \leq 3$, and similarly define $t_j$, $1\leq j\leq 3$ for $P_2$. The payoff matrix is:


$$A=\begin{bmatrix} 0 & 1 & -2\\ -1 & 0 & 1\\ 2 & -1 & 0 \end{bmatrix}$$

By symmetry it is reasonable to expect the value of the game to be 0. To verify and compute optimal strategies, we first add the absolute value of the minimum digit to each of the aboce matrix, giving the following matrix, which corresponds to a game with value at least 1. As all the entries in the last two rows are greater than or equal to 1. 

$$A'=\begin{bmatrix} 2 & 3 & 0\\ 1 & 2 & 3\\ 4 & 1 & 2 \end{bmatrix}$$

The associated linear programming problem corresponding to $P_1$ determination of an optimal strategy and security level is to:
$$Minimize: x_1'+ x_2'+ x_3'$$
Subject to: 

$$ 2x_1'+ 1x_2'+ 4x_3' \geq 1 $$
$$ 3x_1'+ 2x_2'+ 1x_3' \geq 1 $$
$$ 0x_1'+ 3x_2'+ 2x_3' \geq 1 $$
$$ x_1', x_2', x_3' \geq 0 $$


The associated linear programming problem corresponding to $P_2$ determination of an optimal strategy and security level is to:

$$Maximize: y_1'+ y_2'+ y_3'$$
Subject to: 

$$ 2y_1'+ 3y_2'+ 0y_3' \leq 1 $$
$$ 1y_1'+ 2y_2'+ 3y_3' \leq 1 $$
$$ 4y_1'+ 1y_2'+ 2y_3' \leq 1 $$
$$ y_1', y_2', y_3' \geq 0 $$


In [30]:
import numpy as np
from pulp import *

pm=np.array([[ 0, 1,-2],
             [-1, 0, 1],
             [ 2,-1, 0]])

minim_row=np.array([0,0,0])
for i in range(0,len(pm)):
    minim_row[i]=min(pm[i])
    
min_tot=min(minim_row)

pm1=pm+abs(min_tot)

print("Game Matrix:")
print("")
print(pm)
print("")
print("-----------------------------------------------------------------")
print("Equivalent Game Matrix:")
print("")
print(pm1)
print("")
print("-----------------------------------------------------------------")

probx=LpProblem("Game X", LpMinimize)
#The variables are created:
x_1=LpVariable("X_1",0,None)
x_2=LpVariable("X_2",0,None)
x_3=LpVariable("X_3",0,None)
 
#The objective function is added
probx += x_1+x_2+x_3

#Subject to restrictions:
probx +=pm1[0][0]*x_1+pm1[1][0]*x_2+ pm1[2][0]*x_3 >=1
probx +=pm1[0][1]*x_1+pm1[1][1]*x_2+ pm1[2][1]*x_3 >=1
probx +=pm1[0][2]*x_1+pm1[1][2]*x_2+ pm1[2][2]*x_3 >=1

#Solution:
probx.solve()

vx=1/value(probx.objective)
print("Game for Player 1")
print ("")
print ("Game value of Equivalent Game Matrix'v'=", vx)
print ("")
print ("Game value Game Matrix 'w'=", vx-abs(min_tot))
print ("")

x=probx.variables()
X1=vx*(x[0].varValue)
X2=vx*(x[1].varValue)
X3=vx*(x[2].varValue)


print ("P1 Strategy:")
print("")
print ("X1=",X1)
print ("X2=",X2)
print ("X3=",X3)

print ("")
print("-----------------------------------------------------------------")

proby=LpProblem("Game Y", LpMaximize)
#The variables are created:
y_1=LpVariable("Y_1",0,None)
y_2=LpVariable("Y_2",0,None)
y_3=LpVariable("Y_3",0,None)
 
#The objective function is added
proby += y_1+y_2+y_3

#Subject to restrictions:
proby +=pm1[0][0]*y_1+pm1[0][1]*y_2+ pm1[0][2]*y_3 <=1
proby +=pm1[1][0]*y_1+pm1[1][1]*y_2+ pm1[1][2]*y_3 <=1
proby +=pm1[2][0]*y_1+pm1[2][1]*y_2+ pm1[2][2]*y_3 <=1

#Solution:
proby.solve()

vy=1/value(proby.objective)
print("Game for Player 2")
print ("")
print ("Game value of Equivalent Game Matrix'v'=", vy)
print ("")
print ("Game value Game Matrix 'w'=", vy-abs(min_tot))
print ("")

y=proby.variables()
Y1=vy*(y[0].varValue)
Y2=vy*(y[1].varValue)
Y3=vy*(y[2].varValue)


print ("P2 Strategy:")
print("")
print ("Y1=",Y1)
print ("Y2=",Y2)
print ("Y3=",Y3)

print ("")


Game Matrix:

[[ 0  1 -2]
 [-1  0  1]
 [ 2 -1  0]]

-----------------------------------------------------------------
Equivalent Game Matrix:

[[2 3 0]
 [1 2 3]
 [4 1 2]]

-----------------------------------------------------------------
Game for Player 1

Game value of Equivalent Game Matrix'v'= 2.0

Game value Game Matrix 'w'= 0.0

P1 Strategy:

X1= 0.25
X2= 0.5
X3= 0.25

-----------------------------------------------------------------
Game for Player 2

Game value of Equivalent Game Matrix'v'= 2.0

Game value Game Matrix 'w'= 0.0

P2 Strategy:

Y1= 0.25
Y2= 0.5
Y3= 0.25



**Reference:**  
Thie, P., Keough, G. (2008) *An introduction to Linear Programming and Game Theory* John Wiley & Sons, Inc., : United States. Pg. 371