# Games People Play
## Game 3

**Rules**. This game is played just like Game 2, with one minor difference: If $P_1$ elects to pass and $P_2$ elects to raise, both players must add the amount $2b$ to the pot before it is distributed in the usual manner. 

Thus if $P_1$ raises and $P_2$ calls, the stakes are $a+b$; but if $P_1$ passes and $P_2$ raises, the stakes are $a+2b$. It is not at all obvious how $P_1$ should proceed if he is dealt a high card. If he raises he wins eigher $a$ or $a+b$, depending on $P_2$ actions; if he passes, he wins at least $a$; and if $P_2$ raises, he wins $a+2b$. But if $P_2$ expects $P_1$ to always pass if he has a high card, then a raise by $P_1$ indicates that he has a low card, and in such circimustances a raise by $P_2$ will net $P_2$ the amount $a+2b$. Thus, to still bluff successfully with a low card by raising on a low-card hand, it seems that $P_1$ must occasionally raise on a high-card hand. 

The payoff matrix in game 3 is given by:

$$A=\begin{bmatrix} 0 & 0 & a & a \\ -\frac{b}{2} & \frac{b}{2} & -b & 0 \\ \frac{b}{2} & -\frac{b}{2} & a+b & a \\ 0 & 0 & 0 & 0  \end{bmatrix}$$

In [6]:
import numpy as np
from pulp import *

#Game 3

def valor_a_b(a,b):
    x=abs(a)
    y=abs(b)
    l=np.array([x,y])
    return l

va=input("Introduce el valor de a: ")
vb=input("Introduce el valor de b: ")
va=int(va)
vb=int(vb)

values=valor_a_b(va,vb)

A=values[0]
B=values[1]

pm=np.array([[   0,    0,    A,   A],
             [-B/2,  B/2,   -B,   0],
             [ B/2, -B/2,  A+B,   A],
             [   0,    0,    0,   0]])

minim_row=np.array([0.,0.,0.,0.])

for i in range(0,len(pm)):
    minim_row[i]=min(pm[i])
    
min_tot=min(minim_row)

pm1=pm+abs(min_tot)

print("Game Matrix:")
print("")
print(pm)
print("")
print("-----------------------------------------------------------------")
print("Equivalent Game Matrix:")
print("")
print(pm1)


Introduce el valor de a: 3
Introduce el valor de b: 4
Game Matrix:

[[ 0.  0.  3.  3.]
 [-2.  2. -4.  0.]
 [ 2. -2.  7.  3.]
 [ 0.  0.  0.  0.]]

-----------------------------------------------------------------
Equivalent Game Matrix:

[[  4.   4.   7.   7.]
 [  2.   6.   0.   4.]
 [  6.   2.  11.   7.]
 [  4.   4.   4.   4.]]


# Strategy for player 1

In [7]:
probx=LpProblem("Game X", LpMinimize)
#The variables are created:
x_1=LpVariable("X_1",0,None)
x_2=LpVariable("X_2",0,None)
x_3=LpVariable("X_3",0,None)
x_4=LpVariable("X_4",0,None)
 
#The objective function is added
probx += x_1+x_2+x_3+x_4

#Subject to restrictions:
probx += pm1[0][0]*x_1+pm1[1][0]*x_2+ pm1[2][0]*x_3 + pm1[3][0]*x_4 >= 1
probx += pm1[0][1]*x_1+pm1[1][1]*x_2+ pm1[2][1]*x_3 + pm1[3][1]*x_4 >= 1
probx += pm1[0][2]*x_1+pm1[1][2]*x_2+ pm1[2][2]*x_3 + pm1[3][2]*x_4 >= 1
probx += pm1[0][3]*x_1+pm1[1][3]*x_2+ pm1[2][3]*x_3 + pm1[3][3]*x_4 >= 1

#Solution:
probx.solve()

vx=1/value(probx.objective)
print("Game for Player 1")
print ("")
print ("Game value of Equivalent Game Matrix'v'=", vx)
print ("")
print ("Game value Game Matrix 'w'=", vx-abs(min_tot))
print ("")

x=probx.variables()

X1=vx*(x[0].varValue)
X2=vx*(x[1].varValue)
X3=vx*(x[2].varValue)
X4=vx*(x[3].varValue)


print ("P1 Strategy:")
print("")
print ("X1=", X1)
print ("X2=", X2)
print ("X3=", X3)
print ("X4=", X4)

Game for Player 1

Game value of Equivalent Game Matrix'v'= 4.0

Game value Game Matrix 'w'= 0.0

P1 Strategy:

X1= 0.0
X2= 0.5
X3= 0.5
X4= 0.0


# Strategy for player 2

In [9]:
proby=LpProblem("Game Y", LpMaximize)
#The variables are created:
y_1=LpVariable("Y_1",0,None)
y_2=LpVariable("Y_2",0,None)
y_3=LpVariable("Y_3",0,None)
y_4=LpVariable("Y_4",0,None)

 
#The objective function is added
proby += y_1+y_2+y_3+y_4

#Subject to restrictions:
proby +=pm1[0][0]*y_1+pm1[0][1]*y_2+ pm1[0][2]*y_3 + pm1[0][3]*y_4 <=1
proby +=pm1[1][0]*y_1+pm1[1][1]*y_2+ pm1[1][2]*y_3 + pm1[1][3]*y_4 <=1
proby +=pm1[2][0]*y_1+pm1[2][1]*y_2+ pm1[2][2]*y_3 + pm1[2][3]*y_4 <=1
proby +=pm1[3][0]*y_1+pm1[3][1]*y_2+ pm1[3][2]*y_3 + pm1[3][3]*y_4 <=1


#Solution:
proby.solve()

vy=1/value(proby.objective)
print("Game for Player 2")
print ("")
print ("Game value of Equivalent Game Matrix'v'=", vy)
print ("")
print ("Game value Game Matrix 'w'=", vy-abs(min_tot))
print ("")

y=proby.variables()
Y1=vy*(y[0].varValue)
Y2=vy*(y[1].varValue)
Y3=vy*(y[2].varValue)
Y4=vy*(y[3].varValue)


print ("P2 Strategy:")
print("")

print ("Y1=",Y1)
print ("Y2=",Y2)
print ("Y3=",Y3)
print ("Y4=",Y4)

Game for Player 2

Game value of Equivalent Game Matrix'v'= 4.0

Game value Game Matrix 'w'= 0.0

P2 Strategy:

Y1= 0.5
Y2= 0.5
Y3= 0.0
Y4= 0.0


**Reference:**  
Thie, P., Keough, G. (2008) *An introduction to Linear Programming and Game Theory* John Wiley & Sons, Inc., : United States. Pg, 385 and 386.