# Games People Play


## Game 2


**Rules**. The ante, the deal, and the options for $P_1$ are just as in Game 1, and if $P_1$ elects to raise, $P_2$'s options are also as in Game 1. However, if $P_1$ elects to pass, the play is not terminated, but $P_2$ can either pass or raise. If $P_2$ elects to pass, play is terminated and the pot distributed as before. If $P_2$ elects to raise, both he and $P_1$ add an amount $b$ to the pot, and men the pot is distributed as before.

Thus the only difference betwen this game and Game 1 is that if $P_1$ chooses to pass, $P_2$ now has the oportunity to increase the pot to $a+b$, and $P_1$ cannot withdraw if $P_2$ wishes to increase the pot. $P_1$'s strategy set remains the same, but now a strategy for $P_2$ must direct her response to both possible plays of $P_1$. Thus a possible strategy for $P_2$ would be to fold if $P_1$ raises and raise if $P_1$ passes. This strategy is denoted by $(F,R)$, where the first component of the ordered pair is $P_2$'s response to a raise by $P_1$ and the second component is her response to pass, with the obvious abbreviations for fold, call, pass, raise. $P_2$ has four pure strategies, denoted by: $(C,R)$,$(C,P)$,$(F,R)$ and $(F,P)$.

The payoff matrix is 4x4, the eintries again are expected values and are computed just as before. The following matrix results:

$$A=\begin{bmatrix} 0 & 0 & a & a \\ 0 & \frac{b}{2} & -\frac{b}{2} & 0 \\ 0 & -\frac{b}{2} & \frac{2a+b}{2} & a \\ 0 & 0 & 0 & 0  \end{bmatrix}$$


In [1]:
import numpy as np
from pulp import *

#Game 2

def valor_a_b(a,b):
    x=abs(a)
    y=abs(b)
    l=np.array([x,y])
    return l

va=input("Introduce el valor de a: ")
vb=input("Introduce el valor de b: ")
va=int(va)
vb=int(vb)

values=valor_a_b(va,vb)

A=values[0]
B=values[1]

pm=np.array([[0,    0,        A,  A],
             [0,  B/2,     -B/2,  0],
             [0, -B/2,(2*A+B)/2,  A],
             [0,    0,        0,  0]])

minim_row=np.array([0.,0.,0.,0.])

for i in range(0,len(pm)):
    minim_row[i]=min(pm[i])
    
min_tot=min(minim_row)

pm1=pm+abs(min_tot)

print("Game Matrix:")
print("")
print(pm)
print("")
print("-----------------------------------------------------------------")
print("Equivalent Game Matrix:")
print("")
print(pm1)
print("")



Introduce el valor de a: 2
Introduce el valor de b: 3
Game Matrix:

[[ 0.   0.   2.   2. ]
 [ 0.   1.5 -1.5  0. ]
 [ 0.  -1.5  3.5  2. ]
 [ 0.   0.   0.   0. ]]

-----------------------------------------------------------------
Equivalent Game Matrix:

[[ 1.5  1.5  3.5  3.5]
 [ 1.5  3.   0.   1.5]
 [ 1.5  0.   5.   3.5]
 [ 1.5  1.5  1.5  1.5]]



# Strategy for player 1

In [2]:
probx=LpProblem("Game X", LpMinimize)
#The variables are created:
x_1=LpVariable("X_1",0,None)
x_2=LpVariable("X_2",0,None)
x_3=LpVariable("X_3",0,None)
x_4=LpVariable("X_4",0,None)
 
#The objective function is added
probx += x_1+x_2+x_3+x_4

#Subject to restrictions:
probx += pm1[0][0]*x_1+pm1[1][0]*x_2+ pm1[2][0]*x_3 + pm1[3][0]*x_4 >= 1
probx += pm1[0][1]*x_1+pm1[1][1]*x_2+ pm1[2][1]*x_3 + pm1[3][1]*x_4 >= 1
probx += pm1[0][2]*x_1+pm1[1][2]*x_2+ pm1[2][2]*x_3 + pm1[3][2]*x_4 >= 1
probx += pm1[0][3]*x_1+pm1[1][3]*x_2+ pm1[2][3]*x_3 + pm1[3][3]*x_4 >= 1

#Solution:
probx.solve()

vx=1/value(probx.objective)
print("Game for Player 1")
print ("")
print ("Game value of Equivalent Game Matrix'v'=", vx)
print ("")
print ("Game value Game Matrix 'w'=", vx-abs(min_tot))
print ("")

x=probx.variables()

X1=vx*(x[0].varValue)
X2=vx*(x[1].varValue)
X3=vx*(x[2].varValue)
X4=vx*(x[3].varValue)


print ("P1 Strategy:")
print("")
print ("X1=", X1)
print ("X2=", X2)
print ("X3=", X3)
print ("X4=", X4)


Game for Player 1

Game value of Equivalent Game Matrix'v'= 1.4999999925

Game value Game Matrix 'w'= -7.49999995442e-09

P1 Strategy:

X1= 0.0
X2= 0.7000000015
X3= 0.29999999850000003
X4= 0.0


# Strategy for player 2

In [3]:
proby=LpProblem("Game Y", LpMaximize)
#The variables are created:
y_1=LpVariable("Y_1",0,None)
y_2=LpVariable("Y_2",0,None)
y_3=LpVariable("Y_3",0,None)
y_4=LpVariable("Y_4",0,None)

 
#The objective function is added
proby += y_1+y_2+y_3+y_4

#Subject to restrictions:
proby +=pm1[0][0]*y_1+pm1[0][1]*y_2+ pm1[0][2]*y_3 + pm1[0][3]*y_4 <=1
proby +=pm1[1][0]*y_1+pm1[1][1]*y_2+ pm1[1][2]*y_3 + pm1[1][3]*y_4 <=1
proby +=pm1[2][0]*y_1+pm1[2][1]*y_2+ pm1[2][2]*y_3 + pm1[2][3]*y_4 <=1
#proby +=pm1[3][0]*y_1+pm1[3][1]*y_2+ pm1[3][2]*y_3 + pm1[3][3]*y_4 <=1


#Solution:
proby.solve()

vy=1/value(proby.objective)
print("Game for Player 2")
print ("")
print ("Game value of Equivalent Game Matrix'v'=", vy)
print ("")
print ("Game value Game Matrix 'w'=", vy-abs(min_tot))
print ("")

y=proby.variables()
Y1=vy*(y[0].varValue)
Y2=vy*(y[1].varValue)
Y3=vy*(y[2].varValue)
Y4=vy*(y[3].varValue)


print ("P2 Strategy:")
print("")
print ("Y1=",Y1)
print ("Y2=",Y2)
print ("Y3=",Y3)
print ("Y4=",Y4)

Game for Player 2

Game value of Equivalent Game Matrix'v'= 1.49999999249775

Game value Game Matrix 'w'= -7.5022499324e-09

P2 Strategy:

Y1= 0.9999999999985001
Y2= 0.0
Y3= 1.500008392497708e-12
Y4= 0.0


While seeming to offer more variety, this game is not as interesting as the game 1; The payoff matrix has saddle points. The game has value 0 and the optimal strategies for Player 2 is to always choose the first column.

**Reference:**  
Thie, P., Keough, G. (2008) *An introduction to Linear Programming and Game Theory* John Wiley & Sons, Inc., : United States. Pg, 384 and 385.